; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A18C9D9E-3E13-49A1-8543-93B9020607DF}
AppName=SigmaAV
AppVerName=Sigma 1.0.0.39
AppPublisher=F_Computer & XTF_Computer Company
AppPublisherURL=http://sigmaav.wordpress.com
AppSupportURL=http://sigmaav.wordpress.com
AppUpdatesURL=http://sigmaav.wordpress.com
DefaultDirName={pf}\SigmaAV
DefaultGroupName=SigmaAV
InfoBeforeFile=D:\Program Files\Borland\Delphi7\Projects\SigmaAV\readme.txt
OutputDir=E:\The Sigma
OutputBaseFilename=Sigma 1.0.0.39
SetupIconFile=D:\Program Files\Borland\Delphi7\Projects\SigmaAV\icon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\DataBases\*"; DestDir: "{app}\Databases"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Plugins\*"; DestDir: "{app}\Plugins"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\Quarantine\*"; DestDir: "{app}\Quarantine"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\readme.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\Options.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\sigma.rpr"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\update.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\The Sigma\qtintf70.dll"; DestDir: "C:\Windows\System32"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Sigma"; Filename: "{app}\Sigma.exe"
Name: "{group}\{cm:UninstallProgram,Sigma}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\SigmaAV"; Filename: "{app}\Sigma.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Sigma.exe"; Description: "{cm:LaunchProgram,Sigma}"; Flags: nowait postinstall skipifsilent

