; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{19B0D32C-8911-4E27-B4FE-1CA5121BE289}
AppName=SigmaAV
AppVerName=SigmaAV 1.0.0.30
AppPublisher=F_Computer & XTF_Computer Company
AppPublisherURL=sigmaav.wordpress.com
AppSupportURL=sigmaav.wordpress.com
AppUpdatesURL=sigmaav.wordpress.com
DefaultDirName={pf}\SigmaAV
DefaultGroupName=SigmaAV
OutputBaseFilename=setup
SetupIconFile=D:\Program Files\Borland\Delphi7\Projects\SigmaAV\icon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\readme.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\AttackReport.log"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\Options.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\sigma.rpr"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\update.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\DataBases\*"; DestDir: "{app}\Databases"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Program Files\Borland\Delphi7\Projects\SigmaAV\Sigma127\Quarantine\*"; DestDir: "{app}\Quarantine"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\SigmaAV"; Filename: "{app}\Sigma.exe"
Name: "{group}\{cm:UninstallProgram,SigmaAV}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\SigmaAV"; Filename: "{app}\Sigma.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Sigma.exe"; Description: "{cm:LaunchProgram,SigmaAV}"; Flags: nowait postinstall skipifsilent

